FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
  && apt-get install -q -y git cmake make g++ lcov \
      gettext-base jq curl \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

RUN git clone --depth=1 -b main -q https://github.com/google/googletest.git /googletest
WORKDIR /googletest/build
RUN cmake .. && make && make install
RUN rm -rf /googletest

WORKDIR /code
RUN useradd -m -s /bin/bash -u1001 ubuntu
USER ubuntu
